<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GestionCommandes.aspx.cs" Inherits="GestionCommercialWeb.GestionCommandes" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>

        body {
    background: #dfe4ea;
    text-align: center;
    margin: 50px auto;
}
        form#form1 {
    border-radius: 5px;
    background: #a4b0be;
    display: inline-block;
    padding: 50px;
}

span {
    color: #fff;
    text-align: center;
    font-family: system-ui;
}

input {
    background: #ced6e0;
    border: 0;
    padding: 10px;
    border-radius: 3px;
    color: #57606f;
    margin-left: 10px;
}

div {
    margin: 10px;
    text-align: center;
    vertical-align: top;
}

.header > div {
    display: inline-block;
    text-align: left;
}

.header > div {}

.header > div:last-child {
    margin-left: 70px;
}

select {
    background: #ced6e0;
    border: 0;
    color: #57606f;
    padding: 10px;
    margin-left: 10px;
    width: 140px;
    border-radius: 3px;
}

.containerr > div {
    display: inline-block;
}

p {
    color: #fff;
    font-family: system-ui;
}

.gridPlace > div {
    display: inline-block;
}

.gridPlace > div:last-child {
    margin-left: 30px;
}

span#Label1 {
    color: #ffa502;
}

.gridPlace > div:last-child > div:last-child {
    background: #fff;
    padding: 6px;
    border-radius: 3px;
    padding-bottom: 20px;
}

.gridPlace > div:last-child > div:last-child p {
    color: #57606f;
}

input[type="submit"] {
    padding: 10px 25px;
    cursor: pointer;
}

input#Button6 {
    width: 300px;
}

table#GridView1 {
    background: #dfe4ea;
    border-color: #a4b0be;
    color: #57606f;
    font-family: system-ui;
    border-radius: 3px;
    overflow: hidden;
}

th {
    padding: 10px 20px;
}

td {
    padding: 8px 16px;
}
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="header">
            <div>
            <div>
                <span>N Commande : </span>
                <asp:TextBox ID="TextBox1" runat="server" OnTextChanged="TextBox1_TextChanged"></asp:TextBox>
            </div>
            <div>
                <span>Date Commande : </span>
                <asp:TextBox ID="TextBox2" runat="server" TextMode="DateTime"></asp:TextBox>
            </div>
        </div>
        <div>
            <div>
                <span>Code Client : </span>
                <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" OnTextChanged="DropDownList1_TextChanged"></asp:DropDownList>
            </div>
            <div>
                <span>Nom : </span>
                <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
            </div>
            <div>
                <span>Ville : </span>
                <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
            </div>
        </div>
        </div>
        <div class="containerr">
            <div>
                <p>Code Article : </p>
                <asp:DropDownList ID="DropDownList2" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList2_SelectedIndexChanged" OnTextChanged="DropDownList2_TextChanged"></asp:DropDownList>
            </div>
            <div>
                <p>Designation : </p>
                <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
            </div>
            <div>
                <p>PU : </p>
                <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
            </div>
            <div>
                <p>QD : </p>
                <asp:TextBox ID="TextBox7" runat="server"></asp:TextBox>
            </div>
            <div>
                <p>QC : </p>
                <asp:TextBox ID="TextBox8" runat="server"></asp:TextBox>
            </div>
        </div>
        <div class="gridPlace">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"></asp:GridView>
            <div>
                <div><asp:Button ID="Button1" runat="server" Text="Ajouter Ligne" OnClick="Button1_Click" /></div>
                <div><asp:Button ID="Button2" runat="server" Text="Supprimer Ligne" /></div>
                <div><p>Total : </p><asp:Label ID="Label1" runat="server"></asp:Label></div>
            </div>
        </div>
        <div>
            <asp:Button ID="Button3" runat="server" Text="Enregistrer la Commande" OnClick="Button3_Click" />
            <asp:Button ID="Button4" runat="server" Text="Valider la Commande" OnClick="Button4_Click" />
            <asp:Button ID="Button5" runat="server" Text="Saisir un Bon Livraison" OnClick="Button5_Click" />
        </div>
        <asp:Button ID="Button6" runat="server" Text="Bon de Commande" OnClick="Button6_Click" />
    </form>
</body>
</html>
